export enum RecommendationType {
    RECOMMEND_MATRIX_SCIPY = 'RECOMMEND_MATRIX_SCIPY',
    RECOMMEND_MATRIX_CLASS_VECTORIZATION = 'RECOMMEND_MATRIX_CLASS_VECTORIZATION',
    RECOMMEND_MATRIX_ENTITY_VECTORIZATION = 'RECOMMEND_MATRIX_ENTITY_VECTORIZATION',
    RECOMMEND_MATRIX_FUNCTIONALITY_VECTORIZATION_CALLGRAPH = 'RECOMMEND_MATRIX_FUNCTIONALITY_VECTORIZATION_CALLGRAPH',
    RECOMMEND_MATRIX_FUNCTIONALITY_VECTORIZATION_SEQUENCE_ACCESSES = 'RECOMMEND_MATRIX_FUNCTIONALITY_VECTORIZATION_SEQUENCE_ACCESSES'
}
