services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    command: ["mongod", "--noauth"]

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: mono2micro-backend
    container_name: backend
    depends_on:
      - mongo
      - scripts
      - functionality_refactor
    links:
      - mongo
      - scripts
      - functionality_refactor
    hostname: 'localhost'
    ports:
      - 8080:8080
    environment:
      - SCRIPTS_ADDRESS=http://scripts:5002
      - MONGO_DB=mongodb://mongo:27017/mono2micro
      - MONGO_DB_NAME=mono2micro
    restart: unless-stopped
    volumes:
      - ./codebases:/codebases

  scripts:
    build:
      context: ./scripts
    image: mono2micro-scripts
    container_name: scripts
    depends_on:
      - mongo
    links:
      - mongo
    hostname: 'localhost'
    ports:
      - 5002:5002
    environment:
      - PORT=5002
      - CODEBASES_PATH=/codebases/
      - MONGO_DB=mongodb://mongo:27017/mono2micro
      - MONGO_DB_NAME=mono2micro
    restart: unless-stopped
    volumes:
      - ./codebases:/codebases
      - './scripts/:/app'

  functionality_refactor:
    build:
      context: ./tools/functionality_refactor/src
    image: functionality_refactor
    container_name: functionality_refactor
    depends_on:
      - mongo
    links:
      - mongo
    command: /app/web_service
    hostname: 'localhost'
    ports:
      - 5001:5001
    environment:
      - MONGO_DB=mongodb://mongo:27017/mono2micro
      - MONGO_DB_NAME=mono2micro
    restart: unless-stopped
    volumes:
      - ./codebases:/codebases

  frontend:
    build:
      context: ./frontend/
    image: mono2micro-frontend
    container_name: frontend
    depends_on:
      - backend
    links:
      - backend
    ports:
      - 3000:3000
    stdin_open: true
    restart: unless-stopped
    volumes:
      - '/app/node_modules'
      - './frontend/:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  mongodata:
