import React from 'react';
import { ClusterView, clusterViewHelp } from './ClusterView';
import { TransactionView, transactionViewHelp } from './TransactionView';
import { EntityView, entityViewHelp } from './EntityView';
import {FunctionalityRefactorToolMenu, refactorToolHelp} from './FunctionalityRefactorToolMenu';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Popover from 'react-bootstrap/Popover';
import Container from 'react-bootstrap/Container';
import OverlayTrigger from 'react-bootstrap/OverlayTrigger';
import Button from 'react-bootstrap/Button';
import Breadcrumb from 'react-bootstrap/Breadcrumb';
import Dropdown from 'react-bootstrap/Dropdown';
import DropdownButton from 'react-bootstrap/DropdownButton';
import {RepositoryService} from "../../services/RepositoryService";
import AppContext from "./../AppContext";

export const views = {
    CLUSTERS: 'Clusters View',
    TRANSACTION: 'Transaction View',
    ENTITY: 'Entity View',
    REFACTOR: 'Refactorization Tool',
};

export const types = {
    CLUSTER: 0,
    CONTROLLER: 1,
    ENTITY: 2
};

export class Views extends React.Component {
    static contextType = AppContext;

    constructor(props) {
        super(props);

        this.state = {
            codebaseName: this.props.match.params.codebaseName,
            dendrogramName: this.props.match.params.dendrogramName,
            decompositionName: this.props.match.params.decompositionName,
            view: views.REFACTOR
        }

        const service = new RepositoryService();
        service.getTranslation(this.state.codebaseName).then(response => {
            const { updateEntityTranslationFile } = this.context;
            updateEntityTranslationFile(response.data);
        })
        .catch(error => {
            console.log(error);
        });

        this.handleSelectView = this.handleSelectView.bind(this);
        this.getHelpText = this.getHelpText.bind(this);
        this.reloadView = this.reloadView.bind(this);
    }

    handleSelectView(value) {
        this.setState({
            view: value
        });
    }

    getHelpText(view) {
        switch(view) {
            case views.CLUSTERS:
                return clusterViewHelp;
            case views.TRANSACTION:
                return transactionViewHelp;
            case views.ENTITY:
                return entityViewHelp;
            case views.REFACTOR:
                return refactorToolHelp;
            default:
                return null;
        }
    }

    renderBreadCrumbs = () => {
        return (
            <Breadcrumb>
                <Breadcrumb.Item href="/">
                    Home
                </Breadcrumb.Item>
                <Breadcrumb.Item href="/codebases">
                    Codebases
                </Breadcrumb.Item>
                <Breadcrumb.Item href={`/codebases/${this.state.codebaseName}`}>
                    {this.state.codebaseName}
                </Breadcrumb.Item>
                <Breadcrumb.Item href={`/codebases/${this.state.codebaseName}/dendrograms`}>
                    Dendrograms
                </Breadcrumb.Item>
                <Breadcrumb.Item href={`/codebases/${this.state.codebaseName}/dendrograms/${this.state.dendrogramName}`}>
                    {this.state.dendrogramName}
                </Breadcrumb.Item>
                <Breadcrumb.Item active>
                    {this.state.decompositionName}
                </Breadcrumb.Item>
            </Breadcrumb>
        );
    }

    /*
    * Not proud but used as an auxiliary function to translate graphs that are generated by default such as the cluster one
    */
    reloadView = () => {
        const aux = this.state.view;

        this.setState({
            view: "",
        }, () => {
            this.setState({
                view: aux,
            })
        });
    }

    render() {
        const helpPopover = (
            <Popover id="helpPopover" title={this.state.view}>
                {this.getHelpText(this.state.view)}
            </Popover>
        );  

        return (
            <Container fluid>
                {this.renderBreadCrumbs()}
                <Row className="mb-2">
                    <Col>
                        <h4 style={{color: "#666666"}}>{this.state.decompositionName}</h4>
                    </Col>
                    <Col>
                        <OverlayTrigger trigger="click" placement="left" overlay={helpPopover}>
                            <Button className="float-right" variant="success">Help</Button>
                        </OverlayTrigger>
                    </Col>
                </Row>
                <Row className="mb-2">
                    <Col sm="auto">
                        <DropdownButton title={this.state.view}>
                            <Dropdown.Item
                                onClick={() => this.handleSelectView(views.CLUSTERS)}
                            >
                                {views.CLUSTERS}
                            </Dropdown.Item>
                            <Dropdown.Item
                                onClick={() => this.handleSelectView(views.TRANSACTION)}
                            >
                                {views.TRANSACTION}
                            </Dropdown.Item>
                            <Dropdown.Item
                                onClick={() => this.handleSelectView(views.ENTITY)}
                            >
                                {views.ENTITY}
                            </Dropdown.Item>
                            <Dropdown.Item
                                onClick={() => this.handleSelectView(views.REFACTOR)}
                            >
                                {views.REFACTOR}
                            </Dropdown.Item>
                        </DropdownButton>
                    </Col>
                    <Col sm={1}>
                        <Button
                            onClick={() => this.reloadView()} 
                            className="mb-2"
                        >
                            Reload
                        </Button>
                    </Col>
                </Row>
                <Row>
                    <Col>
                        {
                            this.state.view === views.CLUSTERS &&
                                <ClusterView
                                    codebaseName={this.state.codebaseName}
                                    dendrogramName={this.state.dendrogramName} 
                                    decompositionName={this.state.decompositionName}
                                />
                        }
                        {
                            this.state.view === views.TRANSACTION &&
                                <TransactionView
                                    codebaseName={this.state.codebaseName}
                                    dendrogramName={this.state.dendrogramName} 
                                    decompositionName={this.state.decompositionName}
                                />
                        }
                        {
                            this.state.view === views.ENTITY &&
                                <EntityView
                                    codebaseName={this.state.codebaseName}
                                    dendrogramName={this.state.dendrogramName} 
                                    decompositionName={this.state.decompositionName}
                                />
                        }
                        {
                            this.state.view === views.REFACTOR &&
                                <FunctionalityRefactorToolMenu 
                                    codebaseName = {this.state.codebaseName}
                                    dendrogramName = {this.state.dendrogramName}
                                    decompositionName = {this.state.decompositionName}
                                />
                        }
                    </Col>
                </Row>
            </Container>
        );
    }
}