package pt.ist.socialsoftware.mono2micro.recommendation.domain;

public class RecommendationsType {

    public static final String RECOMMEND_MATRIX_SCIPY = "RECOMMEND_MATRIX_SCIPY";
    public static final String RECOMMEND_MATRIX_CLASS_VECTORIZATION = "RECOMMEND_MATRIX_CLASS_VECTORIZATION";
    public static final String RECOMMEND_MATRIX_ENTITY_VECTORIZATION = "RECOMMEND_MATRIX_ENTITY_VECTORIZATION";
    public static final String RECOMMEND_MATRIX_FUNCTIONALITY_VECTORIZATION_CALLGRAPH = "RECOMMEND_MATRIX_FUNCTIONALITY_VECTORIZATION_CALLGRAPH";
    public static final String RECOMMEND_MATRIX_FUNCTIONALITY_VECTORIZATION_SEQUENCE_ACCESSES = "RECOMMEND_MATRIX_FUNCTIONALITY_VECTORIZATION_SEQUENCE_ACCESSES";

}
